<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_Service</name>
   <tag></tag>
   <elementGuidId>7624c3de-618c-4170-b161-da69de9b93e7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/items/item-120187-637073061875119586-9IRCdk.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyPrintDiv&quot;)/div[@class=&quot;purhstdtls-content-sec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;purhstdtls-col-sec&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;purhstdtls-seller-sec&quot;]/div[@class=&quot;purhstdtls-seller-img&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
