<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_OrderStatusContent</name>
   <tag></tag>
   <elementGuidId>5a85266a-c7a5-495b-a4ef-7f937a6188f7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fully paid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyPrintDiv&quot;)/div[@class=&quot;purhstdtls-content-sec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;purhstdtls-status-sec&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
