<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_NoteToServiceProvider</name>
   <tag></tag>
   <elementGuidId>e03a5576-4185-4423-95ed-b13ab385b3d1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Note to service provider :</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyPrintDiv&quot;)/div[@class=&quot;purhstdtls-content-sec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;purhstdtls-col-sec&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;purhstdtls-delvry-sec&quot;]/div[@class=&quot;purhstdtls-seller-note&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
