<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_Contact</name>
   <tag></tag>
   <elementGuidId>07c27e23-482c-4060-96aa-b08d766c3fc0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyPrintDiv&quot;)/div[@class=&quot;ordr-dtls-top-area&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row ordr-dtls-top-section&quot;]/div[@class=&quot;ordr-dtls-top-left purchase-pg-hist-dtls-left&quot;]/div[@class=&quot;ordr-dtls-top-left&quot;]/div[@class=&quot;ordr-dtls-buyer-info&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;ordr-dtls-buyer-infoind&quot;]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
