<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>collapse_images</name>
   <tag></tag>
   <elementGuidId>c6c57bca-1ba5-4a3c-9b65-b79dace5c80e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-toggle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HLMN7VMEMU80&quot;)/div[1]/div[1]/div[@class=&quot;main&quot;]/div[@class=&quot;seller-tab-area spacetime-tab-area&quot;]/div[@class=&quot;spacetime_tab-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/ul[1]/li[@class=&quot;tab-images active&quot;]/div[@class=&quot;tab-content-header&quot;]/a[@class=&quot;toggle-tab&quot;]/i[@class=&quot;icon-toggle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
