<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Upload now</name>
   <tag></tag>
   <elementGuidId>403c6b8c-ab2a-4cda-aa10-a9366ebbd06c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>itmupld-loc-upldbtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload now</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location&quot;)/div[@class=&quot;itmupld-location-sec&quot;]/div[@class=&quot;seller-common-box&quot;]/div[@class=&quot;box-shadow&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;itmupld-loc-upldbtnsec&quot;]/a[@class=&quot;itmupld-loc-upldbtn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
