<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_Surcharge</name>
   <tag></tag>
   <elementGuidId>79dd028c-a92b-4fa0-b52e-d3859fbf8e2c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Surcharge</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-item-area-custom-fields&quot;)/div[@class=&quot;box-shadow&quot;]/div[@class=&quot;itmupld-adtnservcs-addonsec&quot;]/div[@class=&quot;itmupld-adtnservcs-addonedit&quot;]/div[@class=&quot;col-sm-3&quot;]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
