<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accept Cookies</name>
   <tag></tag>
   <elementGuidId>a66a86e5-f2e6-4e9e-8897-f944b82a1699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;fixntf_popup_cookies_btm_fixmsg&quot;)/div[@class=&quot;fixntf-rsec&quot;]/a[@class=&quot;fixntf-btn&quot;][count(. | //*[(text() = 'Accept Cookies' or . = 'Accept Cookies')]) = count(//*[(text() = 'Accept Cookies' or . = 'Accept Cookies')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fixnotification_dismiss(this,'cookies_btm_fixmsg');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fixntf-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept Cookies</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fixntf_popup_cookies_btm_fixmsg&quot;)/div[@class=&quot;fixntf-rsec&quot;]/a[@class=&quot;fixntf-btn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
