<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_service</name>
   <tag></tag>
   <elementGuidId>1d20e164-e92f-4340-b7b6-0b4cb3a55c2a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-cog-bg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HLMN7VMEMU80&quot;)/div[1]/div[1]/div[@class=&quot;main&quot;]/div[@class=&quot;seller-tab-area spacetime-tab-area&quot;]/div[@class=&quot;seller-settings-menu-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;seller-settings-title&quot;]/div[@class=&quot;seller-settings-mobile&quot;]/span[@class=&quot;icon-cog-bg&quot;]</value>
   </webElementProperties>
</WebElementEntity>
