<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_cat12</name>
   <tag></tag>
   <elementGuidId>23c71119-075b-46b3-9d12-845d3a41b59e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;add-item-area&quot;]/div/div[1]/div/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[12]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;add-item-area&quot;]/div/div[1]/div/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[12]/label</value>
   </webElementProperties>
</WebElementEntity>
