<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_cat2</name>
   <tag></tag>
   <elementGuidId>e4778424-f6d6-4b33-a28e-c77d9b8c6560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;add-item-area&quot;]/div/div[1]/div/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;add-item-area&quot;]/div/div[1]/div/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[2]/label</value>
   </webElementProperties>
</WebElementEntity>
