<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delivery2</name>
   <tag></tag>
   <elementGuidId>ce3842db-d881-43b0-8f82-9169e8631677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;delivery&quot;]/div/div/div[1]/div/div/div[1]/div[2]/div/div/div[2]/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delivery 2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;delivery&quot;]/div/div/div[1]/div/div/div[1]/div[2]/div/div/div[2]/label/span[2]</value>
   </webElementProperties>
</WebElementEntity>
