<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delivery1</name>
   <tag></tag>
   <elementGuidId>bfa5f37f-c0a8-49df-bb8b-9721746d4945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;delivery&quot;]/div/div/div[1]/div/div/div[1]/div[2]/div/div/div[1]/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delivery 1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;delivery&quot;]/div/div/div[1]/div/div/div[1]/div[2]/div/div/div[1]/label/span[2]</value>
   </webElementProperties>
</WebElementEntity>
