<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_delivery</name>
   <tag></tag>
   <elementGuidId>560b738a-f403-48a5-870b-b51441a52b73</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HLMPIPK1SKPD&quot;)/div[1]/div[1]/div[@class=&quot;main&quot;]/div[@class=&quot;seller-tab-area spacetime-tab-area&quot;]/div[@class=&quot;spacetime_tab-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/ul[1]/li[@class=&quot;tab-delivery completed active&quot;]/div[@class=&quot;tab-content-header&quot;]/a[1]/i[@class=&quot;icon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
