<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>container_address</name>
   <tag></tag>
   <elementGuidId>f9c3c42b-ff93-40f4-9636-b90a10cdc128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;address&quot;]/div/div[2]/div[3]/div[1]/div</value>
   </webElementProperties>
</WebElementEntity>
