<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_1</name>
   <tag></tag>
   <elementGuidId>58ba902a-d8b9-4dcb-8625-21d534e45701</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagination-log&quot;)/div[@class=&quot;paginationjs&quot;]/div[@class=&quot;paginationjs-pages&quot;]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;paginationjs-page J-paginationjs-page active&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
