<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>previous_page</name>
   <tag></tag>
   <elementGuidId>629e03d1-8947-40d4-842b-390ed1fb96d7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>«</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagination-log&quot;)/div[@class=&quot;paginationjs&quot;]/div[@class=&quot;paginationjs-pages&quot;]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;paginationjs-prev disabled&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
