<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_JoinForFree</name>
   <tag></tag>
   <elementGuidId>92ca2d21-0177-4f07-92bc-39e66e7d7c31</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.kinly.co/user/marketplace/customlogin?isSeller=true&amp;returnUrl=https%3A%2F%2Fwww.kinly.co%2F</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Join For Free </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-48897e59-5c31-e811-80d1-000d3aa28ae2&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;section-banner-content&quot;]/div[@class=&quot;button-text&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
