<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_Amalie</name>
   <tag></tag>
   <elementGuidId>1db22ebf-9162-4957-998f-efcd4bf06d90</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images//CoverImage23876-636450409358123837-7Tz94e.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-4b897e59-5c31-e811-80d1-000d3aa28ae2&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;square-img&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
